[package]
name = "aqmon"
version = "0.1.0"
authors = ["Rodrigo Valle <rdan.valle@gmail.com>"]
edition = "2018"

[dependencies]
# this is broken
#ruduino = "0.2"

[profile.release]
codegen-units = 1
lto = true
debug = false
opt-level = "s"
